[[robots]]
robot_description_topic = "/robot_description_isaac"

[robot.mocap_link]
tracked_frame = "base_link"
fixed_frame = "world"
tracked_prim = "/robot/base_link"

[ground.transform]
translation = [ 0.0, 0.0, -0.3,]