#:schema schema.json

[[robots]]
robot_description_topic = "/robot_description_isaac"
publish_ground_truth_tf = true
visualization_mode = false
[robots.realsense_camera]
width = 640
height = 480

[ground.transform]
translation = [ 0.0, 0.0, -0.3,]