#:schema schema.json

[[robots]]
name = "robot"
xacro_path = "path/to/robot.xacro"
visualization_mode = false
visualization_fixed_frame = "world"
[robots.realsense_camera]
width = 640
height = 480

[robots.transform]
translation = [ 0.0, 0.0, 0.1,]
rotation = [ 1.0, 0.0, 0.0, 0.0,]
[[robots]]
name = "robot"
robot_description_topic = "robot_description"
visualization_mode = true
visualization_fixed_frame = "world"

[camera]
translation = [ -0.3577958949555765, -1.1875695366976564, 0.632201840815314,]
target = [ 0.4, 0.4, 0.0,]

[light]
intensity = 1000.0

[ground.transform]
translation = [ 0.0, 0.0, 0.0,]
rotation = [ 1.0, 0.0, 0.0, 0.0,]
