[robot]
xacro_path = "package://ros2_m_hero_pkg/urdf/hero_7dof.xacro"
visualization_mode = true
preserve_joints_of_links_in_visualization_mode = [
    "leg4gripper2_jaw_left",
    "leg4gripper2_jaw_right",
    "leg4gripper1_jaw_right",
    "leg4gripper1_jaw_left",
    "leg4gripper1_base",
    "leg4gripper2_base",
    "leg4link1",
]

[ground.transform]
translation = [0.0, 0.0, -1.0]
