[[robots]]
name = "pallet"
xacro_path = "package://moonbotg_4dof_rppr_ultraslim/urdf/moonbotg_pallet.xacro"
without_controls = true

[[robots]]
robot_description_topic = "/leg1/robot_description"

[robots.transform]
translation = [ -0.4062796372682052, 0.26617423325416073, 0.1966327176404400, ]
rotation = [0.707107, 0.0, 0.0, 0.707107]



[ground.transform]
translation = [ 0.0, 0.0, 0.0,]

