# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_true: true

    ### Controllers available
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      
    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController



### Properties of the controllers that we will use and definition of joints to use ###
forward_position_controller:
  ros__parameters:
    joints:
      - Leg1_Joint1
      - Leg1_Joint2
      - Leg1_Joint3
      - Leg2_Joint1
      - Leg2_Joint2
      - Leg2_Joint3
      - Leg3_Joint1
      - Leg3_Joint2
      - Leg3_Joint3
      - Leg4_Joint1
      - Leg4_Joint2
      - Leg4_Joint3

    interface_name: position
    # command_interfaces:
    #   - effort

    # state_interfaces:
    #   - position
    #   - velocity
    #   - effort

position_trajectory_controller:
  ros__parameters:
    joints:
      - Leg1_Joint1
      - Leg1_Joint2
      - Leg1_Joint3
      - Leg2_Joint1
      - Leg2_Joint2
      - Leg2_Joint3
      - Leg3_Joint1
      - Leg3_Joint2
      - Leg3_Joint3
      - Leg4_Joint1
      - Leg4_Joint2
      - Leg4_Joint3

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 200.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

# robot_dynamics:
#   ros__parameters:
#     frequency: 20.0
#     model_state_frequency: 10.0
#     self_manage: true
#     leg_support_distance: 0.2
#     joint_states: joint_states
#     odometry: /odom_raw
#     joint_controller: position_trajectory_controller
#     effort_controller: /effort_controller/commands