controller_joint_names: ['', 'Leg1_Joint1', 'Leg1_Joint2', 'Leg1_Joint3', 'Leg2_Joint1', 'Leg2_Joint2', 'Leg2_joint3', 'Leg3_Joint1', 'Leg3_Joint2', 'Leg3_Joint3', 'Leg4_Joint1', 'LEg4_Joint2', 'Leg4_Joint3', ]
